enabled=1
label=Terminal
icon=📟
match=/terminal
item_001=▶️|Démarrer|/terminal/console|terminalAction('start'); return false;
item_002=🔁|Redémarrer|/terminal/console|terminalAction('restart'); return false;
item_003=⏹️|Arrêter|/terminal/console|terminalAction('stop'); return false;
item_004=🔄|Recharger|/terminal/console|reloadTerminalFrame(); return false;
item_005=⚙️|Paramètres|/terminal/config
item_006=📜|Logs|/terminal/logs
