enabled=1
label=Terminal config
icon=⚙️
match=/terminal/config
item_001=💾|Sauvegarder|/terminal/config|terminalSaveConfig(false); return false;
item_002=🔁|Sauver + redémarrer|/terminal/config|terminalSaveConfig(true); return false;
item_003=🖥️|Terminal|/terminal/console
