enabled=1
label=Gestionnaire de fichiers
icon=📁
match=/file_manager
item_001=📁|Nouveau|/file_manager|mkDir(); return false;
item_002=⏩|Copier|/file_manager|transfer('copy'); return false;
item_003=🚚|Déplacer|/file_manager|transfer('move'); return false;
item_004=🔒|CHMOD|/file_manager|openChmod(); return false;
item_005=👤|CHOWN|/file_manager|openChown(); return false;
item_006=🗑️|Effacer|/file_manager|deleteItems(); return false;
item_007=📤|Importer|/file_manager|openImportFile(); return false;
item_008=📥|Exporter|/file_manager|exportSelectedFile(); return false;
item_009=▶️|Exécution script|/file_manager|openExecJobPopup(); return false;
