enabled=1
label=Docker general
icon=🐳
match=/docker/containers
item_001=🔄|Pull|#|dockerRunStream('system_stacks_update', this); return false;
item_002=▶|Start|#|dockerRunStream('system_stacks_start', this); return false;
item_003=📋|List|#|dockerRunStream('system_stacks_list', this); return false;
item_004=📜|Log Compose|#|dockerOpenComposeTtyd(); return false;
item_005=▶|Tout démarrer|#|dockerRunDockerAction('start_all', this); return false;
item_006=■|Tout arrêter|#|dockerRunDockerAction('stop_all', this); return false;
item_007=▶|Démarrer Docker|#|dockerRunDockerAction('start_docker_service', this); return false;
item_008=↻|Redémarrer Docker|#|dockerRunDockerAction('restart_docker_service', this); return false;
item_009=■|Arrêter Docker|#|dockerRunDockerAction('stop_docker_service', this); return false;
item_010=⚙️|Options générales|/docker/options
