enabled=1
label=Éditeur Docker Run
icon=🚀
match=/docker/run/edit
item_001=💾|Sauvegarder|#|dockerRunSubmitEditor('save_run'); return false;
item_002=💾|Sauvegarder + fermer|#|dockerRunSubmitEditor('save_run_close'); return false;
item_003=✖|Fermer|#|dockerRunCloseCurrentEditor(); return false;
