enabled=1
label=LAN Docker
icon=🌐
match=/docker/networks
item_001=＋|Ajouter|#|dockerOpenLanModal(); return false;
item_002=🌐|Ollama|#|dockerRunStream('system_stacks_ollama'); return false;
item_003=🧹|Remove Ollama|#|dockerRunStream('system_stacks_remove_ollama'); return false;
