enabled=1
label=gestionnaire-conf
icon=⚙️
match=/system/gestionnaire-conf
item_001=⚙️|Options|/system/gestionnaire-conf/options
item_002=📦|Installation|/system/install
item_003=⬆️|Mise A Jours|/system/update
item_004=🛟|Dépannage|/system/troubleshooting
