enabled=1
label=LAN general
icon=🌐
match=/system/lan
item_001=🌐|Réseau Linux|/system/lan
item_002=⚡|Appliquer|/system/lan/apply
item_003=/static/logo/nft.png|Part-Feu|/system/nftables
item_004=📡|mDNS|/system/mdns
