enabled=1
label=LAN Part-Feu
icon=/static/logo/nft.png
match=/system/nftables
item_001=➕|Ajouter un port|/system/nftables|nftOpenAddModal(); return false;
item_002=▶️|Démarrer|/system/nftables|nftAction('start'); return false;
item_003=⏹️|Arrêter|/system/nftables|nftAction('stop'); return false;
item_004=🧱|Configuration classique|/system/nftables|nftAction('default'); return false;
item_005=🌐|Réseau Linux|/system/lan
