enabled=1
label=Menu personnalise
icon=⚙️
match=/system/personnalisation/menu
item_001=📁|+ Dossier|javascript:personalAddFolder()
item_002=➕|+ Commande|javascript:personalAddCommand()
item_003=🔝|Menu top|/system/personnalisation/menu-top
