enabled=1
label=meteo
icon=🌤️
match=/system/personnalisation/meteo
item_001=➕|Ajouter|/system/personnalisation/meteo|meteoOpenModal('meteoAddModal'); return false;
item_002=⇅|Modifier ordre|/system/personnalisation/meteo|meteoOpenModal('meteoOrderModal'); return false;
item_003=🗑️|Supprimer|/system/personnalisation/meteo|meteoOpenModal('meteoDeleteModal'); return false;
item_004=🏠|<- Retour|/system/personnalisation/home
