enabled=1
label=Personnalisation
icon=🎨
match=/system/personnalisation
item_001=🏠|Accueil|/system/personnalisation/home
item_002=🔝|Top|/system/personnalisation/top
item_003=💾|Disque|/system/personnalisation/disque
item_004=📱|Mobile|/system/personnalisation/mobile
item_005=🧭|Menu|/system/personnalisation/menu
item_006=🔝|Menu top|/system/personnalisation/menu-top
item_007=⌨️|Menu CLI|/system/personnalisation/menu-cli
item_008=🌤️|Meteo|/system/personnalisation/meteo
item_009=ℹ️|Info|/system/personnalisation/info
