enabled=1
label=Creer backup
icon=/static/logo/Backup.png
match=/system/uibackup
item_001=/static/logo/Backup.png|Creer backup|#|uibackupCreateBackup(); return false;
item_002=↩|Restaurer|#|uibackupRestoreSelectedBackup(); return false;
item_003=×|Supprimer|#|uibackupDeleteSelectedBackup(); return false;
