enabled=1
label=Archive general
icon=💾
match=/services/archive/general
item_001=➕|Nouveau profil|/services/archive/general|addProfile(); return false;
item_002=🧪|Vérifier archive.conf|/services/archive/general|checkArchiveFromButton(this); return false;
item_003=⏹️|Arrêter|/services/archive/general|stopCurrentArchive(this); return false;
item_004=ℹ️|Info|/services/archive/system
item_005=📜|Logs|/services/archive/logs
