enabled=1
label=Backup general
icon=/static/logo/Backup.png
match=/services/backup/main
item_001=➕|Créer...|/services/backup/create
item_002=⚙️|Réglages|/services/backup/setting
item_003=📘|Lexique|/services/backup/lexique
item_004=📜|Log|/services/backup/log
item_005=ℹ️|Info|/services/backup/info
