enabled=1
label=Cache general
icon=⚡
match=/services/cache/general
item_001=➕|Nouveau profil|/services/cache/general|addCacheProfile(); return false;
item_002=🧪|Vérifier cache.conf|/services/cache/general|checkCacheConf(this); return false;
item_003=⏹️|Arrêter|/services/cache/general|stopCacheJob(this); return false;
item_004=ℹ️|Info|/services/cache/info
item_005=📜|Logs|/services/cache/logs
