enabled=1
label=MiniDLNA
icon=📡
match=/services/minidnla
item_001=🔁|Redémarrer MiniDLNA|/services/minidlna/main|miniPostAction('/services/minidnla/service/action', 'restart', this); return false;
item_002=⬇️|Installer service|/services/minidlna/main|miniPostAction('/services/minidnla/system/action', 'install', this); return false;
item_003=🧩|Appliquer service|/services/minidlna/main|miniPostAction('/services/minidnla/system/action', 'apply', this); return false;
item_004=🗂️|Reconstruire la base|/services/minidlna/main|miniPostAction('/services/minidnla/system/action', 'rebuild_db', this); return false;
item_005=🔧|Droits runtime|/services/minidlna/main|miniPostAction('/services/minidnla/system/action', 'fix_runtime_rights', this); return false;
item_006=🗑️|Supprimer service|/services/minidlna/main|miniPostAction('/services/minidnla/system/action', 'remove_service', this); return false;
item_007=ℹ️|Info|/services/minidnla/info
item_008=📜|Log|/services/minidnla/logs
