--- Stacks YML ---
Install Stacks = stacks.py --update
,Option Stacks...
,Démarrer les Dockers = stacks.py --start
,Affioche les Stacks = stacks.py --list
,install LAN Ollama = stacks.py --ollama
,Remove Ollama LAN = stacks.py --remove-ollama
--- Docker ---
Docker - SAVE tous = docker_cli.py --save
Docker - LOAD tous = docker_cli.py --load
,Option Dockers...
,Docker - SAVE choisir = docker_cli.py --select --save
,Docker - LOAD choisir = docker_cli.py --select --load
,Docker - Liste complète = docker_cli.py --list all
--- Registre ---
Netoyer de Registre = registry.py
--- Cache ---
Vider le Cache = cache.py --all
--- Update ---
Update PIP = bash /yoleo/system/update_pip.sh
System ADD = bash /yoleo/system/system.sh -add
Systerm RESTART = bash /yoleo/system/system.sh -restart
